spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_db_i
    username: garcihard
    password: pwd1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
