version: "3.9"

services:
  postgres:
    container_name: dev_postgres
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "4321:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dev_postgres_data:/var/lib/postgres/data
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  dev_postgres_data:
    driver: local